version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=Dev_UBMarketplace
      - POSTGRES_PASSWORD=Dev_Password123
      - POSTGRES_DB=Dev_UBMarketplace
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql-data/:/var/lib/postgresql/data/
  web:
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run -Dspring-boot.run.arguments=--server.port=8080
    depends_on:
      - postgres

