version: '3'
services:
  mongodb:
    container_name: mongodb
    image: mongo:3.6
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - "27017:27017"
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  web:
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run -Dspring-boot.run.arguments=--server.port=8080
    depends_on:
      - mongodb
